//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.FOE.Server.UnitTests.FOEServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/com.FOE.Server.WebService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://code.google.com/p/FOE/namespace/20120125", ConfigurationName="FOEServiceReference.IFOEService")]
    public interface IFOEService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://code.google.com/p/FOE/namespace/20120125/IFOEService/GetData", ReplyAction="http://code.google.com/p/FOE/namespace/20120125/IFOEService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://code.google.com/p/FOE/namespace/20120125/IFOEService/GetDataUsingDataContr" +
            "act", ReplyAction="http://code.google.com/p/FOE/namespace/20120125/IFOEService/GetDataUsingDataContr" +
            "actResponse")]
        com.FOE.Server.UnitTests.FOEServiceReference.CompositeType GetDataUsingDataContract(com.FOE.Server.UnitTests.FOEServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://code.google.com/p/FOE/namespace/20120125/IFOEService/AddUser", ReplyAction="http://code.google.com/p/FOE/namespace/20120125/IFOEService/AddUserResponse")]
        com.FOE.Server.Interface.FOEResult<com.FOE.DataModel.Users.User> AddUser(string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFOEServiceChannel : com.FOE.Server.UnitTests.FOEServiceReference.IFOEService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FOEServiceClient : System.ServiceModel.ClientBase<com.FOE.Server.UnitTests.FOEServiceReference.IFOEService>, com.FOE.Server.UnitTests.FOEServiceReference.IFOEService {
        
        public FOEServiceClient() {
        }
        
        public FOEServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FOEServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FOEServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FOEServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public com.FOE.Server.UnitTests.FOEServiceReference.CompositeType GetDataUsingDataContract(com.FOE.Server.UnitTests.FOEServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public com.FOE.Server.Interface.FOEResult<com.FOE.DataModel.Users.User> AddUser(string userName, string password) {
            return base.Channel.AddUser(userName, password);
        }
    }
}
