<?xml version="1.0" encoding="utf-8"?><Database Name="Hackenberg" Class="HackenbergDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HIQ-LUND-114\SQLEXPRESS;Initial Catalog=Hackenberg;Integrated Security=True" SettingsObjectName="com.Hackenberg.Server.DataAccess.Properties.Settings" SettingsPropertyName="HackenbergConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DB_SessionMembers" Member="DB_SessionMembers">
    <Type Name="DB_SessionMember">
      <Column Name="SessionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DB_Session_DB_SessionMember" Member="DB_Session" ThisKey="SessionId" OtherKey="Id" Type="DB_Session" IsForeignKey="true" />
      <Association Name="DB_User_DB_SessionMember" Member="DB_User" ThisKey="UserId" OtherKey="Id" Type="DB_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Sessions" Member="DB_Sessions">
    <Type Name="DB_Session">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DB_Session_DB_SessionMember" Member="DB_SessionMembers" ThisKey="Id" OtherKey="SessionId" Type="DB_SessionMember" />
      <Association Name="DB_Session_DB_Game" Member="DB_Games" ThisKey="Id" OtherKey="SessionId" Type="DB_Game" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Users" Member="DB_Users">
    <Type Name="DB_User">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="DB_User_DB_SessionMember" Member="DB_SessionMembers" ThisKey="Id" OtherKey="UserId" Type="DB_SessionMember" />
      <Association Name="DB_User_DB_Country" Member="DB_Countries" ThisKey="Id" OtherKey="ControlledBy" Type="DB_Country" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Maps" Member="DB_Maps">
    <Type Name="DB_Map">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DB_Map_DB_Game" Member="DB_Games" ThisKey="Id" OtherKey="MapId" Type="DB_Game" />
      <Association Name="DB_Map_DB_MapCountry" Member="DB_MapCountries" ThisKey="Id" OtherKey="MapId" Type="DB_MapCountry" />
    </Type>
  </Table>
  <Table Name="dbo.DB_GameRules" Member="DB_GameRules">
    <Type Name="DB_GameRule">
      <Column Name="RuleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DB_Rule_DB_GameRule" Member="DB_Rule" ThisKey="RuleId" OtherKey="Id" Type="DB_Rule" IsForeignKey="true" />
      <Association Name="DB_Game_DB_GameRule" Member="DB_Game" ThisKey="GameId" OtherKey="Id" Type="DB_Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Rules" Member="DB_Rules">
    <Type Name="DB_Rule">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Effect" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="DB_Rule_DB_GameRule" Member="DB_GameRules" ThisKey="Id" OtherKey="RuleId" Type="DB_GameRule" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Games" Member="DB_Games">
    <Type Name="DB_Game">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SessionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="MapId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Phase" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Turn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DB_Game_DB_GameRule" Member="DB_GameRules" ThisKey="Id" OtherKey="GameId" Type="DB_GameRule" />
      <Association Name="DB_Map_DB_Game" Member="DB_Map" ThisKey="MapId" OtherKey="Id" Type="DB_Map" IsForeignKey="true" />
      <Association Name="DB_Session_DB_Game" Member="DB_Session" ThisKey="SessionId" OtherKey="Id" Type="DB_Session" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_MapCountries" Member="DB_MapCountries">
    <Type Name="DB_MapCountry">
      <Column Name="MapId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DB_Map_DB_MapCountry" Member="DB_Map" ThisKey="MapId" OtherKey="Id" Type="DB_Map" IsForeignKey="true" />
      <Association Name="DB_Country_DB_MapCountry" Member="DB_Country" ThisKey="CountryId" OtherKey="Id" Type="DB_Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Countries" Member="DB_Countries">
    <Type Name="DB_Country">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ControlledBy" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DB_Country_DB_MapCountry" Member="DB_MapCountries" ThisKey="Id" OtherKey="CountryId" Type="DB_MapCountry" />
      <Association Name="DB_Country_DB_CountryForce" Member="DB_CountryForces" ThisKey="Id" OtherKey="CountryId" Type="DB_CountryForce" />
      <Association Name="DB_Country_DB_CountryStructure" Member="DB_CountryStructures" ThisKey="Id" OtherKey="CountryId" Type="DB_CountryStructure" />
      <Association Name="DB_User_DB_Country" Member="DB_User" ThisKey="ControlledBy" OtherKey="Id" Type="DB_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_CountryForces" Member="DB_CountryForces">
    <Type Name="DB_CountryForce">
      <Column Name="ForceId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DB_Country_DB_CountryForce" Member="DB_Country" ThisKey="CountryId" OtherKey="Id" Type="DB_Country" IsForeignKey="true" />
      <Association Name="DB_Force_DB_CountryForce" Member="DB_Force" ThisKey="ForceId" OtherKey="Id" Type="DB_Force" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Forces" Member="DB_Forces">
    <Type Name="DB_Force">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefenceStrength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OffenceStrength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DB_Force_DB_CountryForce" Member="DB_CountryForces" ThisKey="Id" OtherKey="ForceId" Type="DB_CountryForce" />
    </Type>
  </Table>
  <Table Name="dbo.DB_CountryStructures" Member="DB_CountryStructures">
    <Type Name="DB_CountryStructure">
      <Column Name="CountryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StructureId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DB_Country_DB_CountryStructure" Member="DB_Country" ThisKey="CountryId" OtherKey="Id" Type="DB_Country" IsForeignKey="true" />
      <Association Name="DB_Structure_DB_CountryStructure" Member="DB_Structure" ThisKey="StructureId" OtherKey="Id" Type="DB_Structure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Structures" Member="DB_Structures">
    <Type Name="DB_Structure">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Effect" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="DB_Structure_DB_CountryStructure" Member="DB_CountryStructures" ThisKey="Id" OtherKey="StructureId" Type="DB_CountryStructure" />
    </Type>
  </Table>
</Database>